{% set name = "ibis-heavyai" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ibis-heavyai-{{ version }}.tar.gz
  sha256: d4dbf1e5f151408d00073812fb62c40285cc3a481d146b44cc63d4c2d4cf81fd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core
  run:
    - python >={{ python_min }}
    - ibis-framework >=2.0, <3
    - heavyai
    - rbc >=0.8.0
    - pyarrow >=3.0.0
    - regex
    - pandas
    - shapely
    - geopandas
    - importlib_metadata
    - packaging

test:
  requires:
    - python {{ python_min }}
  imports:
    - ibis_heavyai

about:
  home: https://github.com/heavyai/ibis-heavyai
  summary: Ibis HeavyDB backend
  dev_url: https://github.com/heavyai/ibis-heavyai
  doc_url: https://github.com/heavyai/ibis-heavyai/docs/heavyai.rst
  license: Apache-2.0
  license_file: LICENSE.md
  description: |
    Ibis is a Python framework to write data analytics code, in a similar way
    to pandas. Ibis can execute the queries not only in memory
    (as pandas does), but in different backends, including SQL databases,
    and analytics databases, like HeavyDB. HeavyDB is SQL-based, relational,
    columnar and specifically developed to harness the massive parallelism of
    modern CPU and GPU hardware. OmniSciDB can query up to billions of rows in
    milliseconds, and is capable of unprecedented ingestion speeds, making it
    the ideal SQL engine for the era of big, high-velocity data.

extra:
  recipe-maintainers:
    - tupui
    - pearu
    - andrewseidl
